export const SIGN_OUT = 'SIGN_OUT';
export const INIT_STORE_LOCALSTORAGE = 'INIT_STORE_LOCALSTORAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_MESSAGE_HISTORY = 'FETCH_MESSAGE_HISTORY';
